const axios = require("axios");
const fs = require("fs");
const dotenv = require("dotenv");
dotenv.config();

// const reader = require("xlsx");
// const path = "C:/Users/julio/Downloads/Demo Day C6.xlsx"
// const file = reader.readFile(path)
// const sheets = file.SheetNames

const currentCohort = "C6";
const currentSelection = "S3";

let emails = [
  "wnorowsky.nicolas@gmail.com",
  "alexmarinmendez@gmail.com",
  "romero.nico18@gmail.com",
  "orlandoneris24@gmail.com",
  "juan.molina159@gmail.com",
  "villacresa@gmail.com",
  "felipe.calderon321@gmail.com",
  "pablocdm08@gmail.com",
  "martinkunbrc@hotmail.com",
  "luiggimera01@gmail.com",
  "emanuel_c400@hotmail.com",
  "villenmj@gmail.com",
  "jonathandanielarce9@gmail.com",
  "stiwers1997@gmail.com",
  "svrk73@gmail.com",
  "davidmedev@gmail.com",
  "arielstereo@msn.com",
  "zonajl@gmail.com",
  "duranlautarogabriel@gmail.com",
  "alexismesac@gmail.com",
  "rodri.br18@gmail.com",
  "ricardoibarra2044@gmail.com",
  "ale_lasarte@hotmail.com",
  "ederromero32@gmail.com",
  "evilld94@gmail.com",
  "angie.becerra94@gmail.com",
  "azarjpm15@gmail.com",
  "mjparedes2505@gmail.com",
  "cereceda1991@gmail.com",
  "exedevcoding22@gmail.com",
  "contactame@rafaelaestevesg.com",
  "deme12.1@gmail.com",
  "dematteiteo@gmail.com",
  "soto_tania@hotmail.com",
  "cintiacrifo@gmail.com",
  "maxiicarp88@gmail.com",
  "matiasc.02.2003@gmail.com",
  "diego.productividad@gmail.com",
  "ricardoandrestolomei@gmail.com",
  "percytejada.code@gmail.com",
  "marcoslopezdev18@gmail.com",
  "angie00069@gmail.com",
  "dnazariego@gmail.com",
  "aguss.97@outlook.com",
  "deivi.jimenez@gmail.com",
  "roddericckk@gmail.com",
  "marcopdonoso@gmail.com",
  "rafaelstrongoli@gmail.com",
  "jjnicoramirez@gmail.com",
  "arenca44@gmail.com",
  "matias.henriquez.dev@gmail.com",
  "ivanrovner7@gmail.com",
  "jorgeahenriqueznovoa@gmail.com",
  "pauli.sancho@gmail.com",
  "exequielbaez@gmail.com",
  "lguzman.58erb@outlook.com",
  "parra.roger05@gmail.com",
  "jjd21017@gmail.com",
  "v1c70rotakmer@gmail.com",
  "victor.d.araya@gmail.com",
  "agustinprato56@gmail.com",
  "alekosescu@gmail.com",
  "diegoromero.dr021@gmail.com",
  "facundoagueroc@gmail.com",
  "csaggio74@hotmail.com",
  "freddymoya2013@gmail.com",
  "para.solarmani@gmail.com",
  "christian.ivan.cachero@gmail.com",
  "g__56@hotmail.com",
  "luz.tabrajb@gmail.com",
  "pachecoabimael360@gmail.com",
  "deydrim.dg@gmail.com",
  "leonasturizaga@gmail.com",
  "arnoldfelce2@gmail.com",
  "jovahinrivera@gmail.com",
  "inkantador@gmail.com",
  "ariadna.dalleth.vazquez@gmail.com",
  "matias.nicolas.acevedo@gmail.com",
  "gabyapd05@gmail.com",
  "aylen.s.martel@gmail.com",
  "freremarialuz@gmail.com",
  "antostaffolani@gmail.com",
  "rodrigocordoneda@gmail.com",
  "rocha.nahuel@hotmail.com",
  "cheloperalta22@gmail.com",
  "esimpatica2013@gmail.com",
  "baesp2022@gmail.com",
  "michellangelasierra@gmail.com",
  "ing.elbaum@gmail.com",
  "omar.mejia2099@gmail.com",
  "santiagoperezkay88@gmail.com",
  "pablor.velasco.suarez@gmail.com",
  "camiloduquee@gmail.com",
  "orlandocardenas0107@gmail.com",
  "monicadiazgarzon@gmail.com",
  "yordychoque124@gmail.com",
  "rodrigogeorgetti.cba@gmail.com",
  "charata.01@gmail.com",
  "brandonahumada804@gmail.com",
  "cristiandalpiva@hotmail.com",
  "francotorrico1999@gmail.com",
  "matiasss95@gmail.com",
  "pat.fernandez20@gmail.com",
  "santiagoo.vergaraa@gmail.com",
  "ad.contacto7@gmail.com",
  "romanat94@gmail.com",
  "liviagarrido7@gmail.com",
  "damian.fernandez.dev@gmail.com",
  "fn.margutti@gmail.com",
  "staricofflionel@gmail.com",
  "santigonzalez.dev@gmail.com",
  "edslavianov@gmail.com",
  "fabianmanrique10@gmail.com",
  "ingeniera-yazuline@hotmail.com",
  "pachecolobos.felix@gmail.com",
  "joseobando30@gmail.com",
  "pablo_spector@hotmail.com",
  "sofia15ba@gmail.com",
  "ximenaellis@gmail.com",
  "molinamonroyv@gmail.com",
  "woldehtes@gmail.com",
  "mayrakcoronel@gmail.com",
  "naticanizatoral@gmail.com",
  "lrfernandez.cortez@gmail.com",
  "petterssonfacundo@gmail.com",
  "chavez.miguel.angel154@gmail.com",
  "d.berrojalvis@gmail.com",
  "ezealeguzman@gmail.com",
  "johannmgr@gmail.com",
  "jgp.workmail@gmail.com",
  "antho7294@gmail.com",
  "mymarce27@gmail.com",
  "juanignaciolobo97@gmail.com",
  "medinafacundom@gmail.com",
  "tomasaquinogabi@gmail.com",
  "angelacba86@gmail.com",
  "alexdam36@gmail.com",
  "lunajosiasm@gmail.com",
  "omarnlujan@gmail.com",
  "javier17utn@gmail.com",
  "goodfriend_18@hotmail.com",
  "alejandro_0793@hotmail.com",
  "sashasawosz@hotmail.com",
  "cristiangomez0686@outlook.com",
  "luciafgangi@hotmail.com",
  "nicolastortosa91@gmail.com",
  "castillicatrifol@gmail.com",
  "mquirico10@gmail.com",
  "alvaroamestoycontact@gmail.com",
  "rocioclaus@gmail.com",
  "guebe.braga5@gmail.com",
  "alvaromirandamita@gmail.com",
  "mdonattiprogramacion@gmail.com",
  "silvia.alinacr@gmail.com",
  "guillecarck@gmail.com",
  "juanignacionovas@gmail.com",
  "verasdiegoca78@gmail.com",
  "jeni20suarez@gmail.com",
  "cristian.ceronb@gmail.com",
  "estefaniaochoah@gmail.com",
  "joselbcontreras@gmail.com",
  "angelsuarez2612@gmail.com",
  "joaku_14@hotmail.com",
  "preciadovaleriam@gmail.com",
  "dearribamalena@gmail.com",
  "quinteroenrrique321@gmail.com",
  "saig.matias@gmail.com",
  "danitzavitoviz@gmail.com",
  "catriellescobar@gmail.com",
  "alixeth15@hotmail.com",
  "pedronuca3@gmail.com",
  "erhh.015@gmail.com",
  "angel.salazarmaylle@gmail.com",
  "maximilianoingeniero@gmail.com",
  "lissbethescobar09@gmail.com",
  "nr.rovere@gmail.com",
  "david.yanez.epn@gmail.com",
  "chrisday2009@hotmail.com",
  "amontesvega2191@gmail.com",
  "mcgargentina@gmail.com",
  "rosvir16@gmail.com",
  "martinezfenix99@gmail.com",
  "fernandezjuanjc@gmail.com",
  "rdminhot@gmail.com",
  "cesar.s.mlopez@gmail.com",
  "veronica.derosa@gmail.com",
  "tmjhosep@gmail.com",
  "jaruiz721818@gmail.com",
  "ivann-gonzalez@hotmail.com",
  "brendacomasok@gmail.com",
  "gleonardo.cortes@gmail.com",
  "thomasignaciolopez@gmail.com",
  "yuiftw05@gmail.com",
  "marianopoulsen93@gmail.com",
  "liss.malave@gmail.com",
  "verobravo112012@gmail.com",
  "angdavid2910@gmail.com",
  "trianadevia@gmail.com",
  "alguien4598@gmail.com",
  "jhony.fori@gmail.com",
  "lupfaff3@gmail.com",
  "arco527@gmail.com",
  "leivanaomi.b@gmail.com",
  "jandrad38807@gmail.com",
  "juanmanuelramoslencina@gmail.com",
  "javiercolodro@gmail.com",
  "aldo.mmm@hotmail.com",
  "sbenjacarias@gmail.com",
  "fedemerediz@hotmail.com",
  "timonrock2015@gmail.com",
  "drdanielreyes5@gmail.com",
  "rafaelgauna123@gmail.com",
  "francovangaray1@gmail.com",
  "joseimascherpa@gmail.com",
  "gergati1994@gmail.com",
  "fabiocroldan@gmail.com",
  "garcia17h@gmail.com",
  "jtrvic7@gmail.com",
  "matiasuzumy@gmail.com",
  "gerardo.carrizo123.gc@gmail.com",
  "christian.kase@hotmail.com",
  "mersingwalter@gmail.com",
  "scanevaro87@gmail.com",
  "jcastroprogrammer@hotmail.com",
  "duvanaponteramirez@gmail.com",
  "dbhrnf@gmail.com",
  "facagre@gmail.com",
  "retromantis@hotmail.com",
  "silviainesvillalba@gmail.com",
  "lizethvelasco.20@gmail.com",
  "juansincich@gmail.com",
  "pmsaraalcantara@gmail.com",
];

console.log(emails);

async function processDemoDay() {
  //Si hay miembros del seleccionado que no aprobaron, debemos bajarlos /filtertofalse
  if (emails.length > 0) {
    for (let i = 0; i < emails.length; i++) {
      try {
        //Llamamos a bajar del seleccionado
        let res = await axios.put(
          `${process.env.LOCALHOST}selection/filterpassed/`,
          {
            email: emails[i],
            filter: true,
          }
        );

        //Agrego a salida
        console.log(i + " Procesado OK: " + emails[i]);
      } catch (error) {
        console.log(i + " No se pudo procesar: " + emails[i]);
      }
    }
  }

  // if (output.length > 1) {

  //     const d = new Date()
  //     const time = '' + d.getHours() + '-' + d.getMinutes() + '-' + d.getSeconds()
  //     let fullnamesWithSpace = output.join('\n')
  //     fs.writeFileSync(`C:/NC/NC-Consultas/output/LogDemoDay${time}.csv`, fullnamesWithSpace);

  // }
}

processDemoDay();
