const readXlsxFile = require("read-excel-file/node");
const axios = require("axios");
const fs = require("fs");
const dotenv = require("dotenv");
dotenv.config();
const reader = require("xlsx");
const noCodeTeam = "S5-no-code";
const asd = "C:/Users/Administrator/Desktop/NC/Calificaciones/S9.xlsx";

const emails = [
  "gabriel.nohra@gmail.com",
  "cristobal.npe@gmail.com",
  "camila.rotundo@gmail.com",
  "vivanco.elsa@gmail.com",
  "surii2908@gmail.com",
  "mauri.monzon91@gmail.com",
  "shuertas981@gmail.com",
  "noecoast@gmail.com",
  "gianellaachetoni@gmail.com",
  "leonmateocaceres705@gmail.com",
  "nava_ignacio@outlook.com",
  "caritos22@hotmail.com",
  "ballesty.t@gmail.com",
  "ivanrga@hotmail.com.ar",
  "joelfernandez.relg@gmail.com",
  "valdesmartin@gmail.com",
  "claudiaruizone@gmail.com",
  "sosaian@proton.me",
  "marianoledezma@gmail.com",
  "florenciaviale@hotmail.com",
  "solerivero1994@gmail.com",
  "ambarramon14@gmail.com",
  "cesarhernanruscica@gmail.com",
  "pepoterrax@gmail.com",
  "robertogial@gmail.com",
  "curojefferson123@gmail.com",
  "alexgabrielfioquetti@gmail.com",
  "kevinlautarosoto@gmail.com",
  "joelaguilarandres@gmail.com",
  "kyaclo.82@gmail.com",
  "elgatoberdaguer@gmail.com",
  "jaimeagalvezv@gmail.com",
  "dmitrijrapach@gmail.com",
  "fjcvillacorta@gmail.com",
  "katiaberriosmo@gmail.com",
  "gabiand1.gs@gmail.com",
  "gonzalezmigdlys@gmail.com",
  "fhdzleon@gmail.com",
  "salces.borges.atlaros@gmail.com",
  "sarto.lali@gmail.com",
  "agustin.ibarra.c@gmail.com",
  "jpachecoim044@gmail.com",
  "leonardofuentesclaros@gmail.com",
  "joseangelgarces123@gmail.com",
  "candelaabril45@gmail.com",
  "ejrb1234@gmail.com",
  "camilaberlincourt.uxui@gmail.com",
  "staricofflionel@gmail.com",
  "javielisrondon@gmail.com",
  "olartealejandro48@gmail.com",
  "zapatacamilo86@gmail.com",
  "walkiarteaga@gmail.com",
  "luisfelipe.azocar@gmail.com",
  "andres.segura.dev@gmail.com",
  "bebo.garavano@gmail.com",
  "tester.passalia@gmail.com",
  "lidevoto@gmail.com",
  "luceldasilva@yahoo.com",
  "elvizvida@gmail.com",
  "azamefranco@gmail.com",
  "madazv7@gmail.com",
  "nayluclash@gmail.com",
  "wilmerhenrysalazarmartinez@gmail.com",
  "davidmedev@gmail.com",
  "dizeoc@gmail.com",
  "4xur174@gmail.com",
  "drojas.avellaneda@gmail.com",
  "limachijosefina.d@gmail.com",
  "julljoll@gmail.com",
  "eliasdcespedespinedo@gmail.com",
  "nicolasadorable16@gmail.com",
  "alicias41086@gmail.com",
  "bareirogabriela819@gmail.com",
  "4maferal@gmail.com",
  "stefanycs91@hotmail.com",
  "sandroborga@gmail.com",
  "gaston.delafuente@gmail.com",
  "kevinrodallega@gmail.com",
  "gran.esoj@gmail.com",
  "marigafer82@gmail.com",
  "mati.bazan97@gmail.com",
  "jmgg.gutierrez@gmail.com",
  "ladyivon_27@hotmail.com",
  "sebas.rengi@hotmail.com",
  "misaa023@gmail.com",
  "mar.pazbello@gmail.com",
  "juanelissalde2002@gmail.com",
  "rassiel.mex@gmail.com",
  "asilvamagali@gmail.com",
  "holasoyviole@gmail.com",
  "r.martinezabraham@gmail.com",
  "tomasvil2125@gmail.com",
  "elvinmoreno2301@gmail.com",
  "angelacvargas2004@gmail.com",
  "angeliquintero39@gmail.com",
  "agus.bosaz1@gmail.com",
  "ma.agustina.cuello@gmail.com",
  "leanmsan@gmail.com",
  "d.berrojalvis@gmail.com",
  "chavez.miguel.angel154@gmail.com",
  "pedronuca3@gmail.com",
  "agustin.merlino@hotmail.com",
  "jntorres2012@gmail.com",
  "jgp.workmail@gmail.com",
  "dantesandoval.dev@gmail.com",
  "lautarojimenez02@gmail.com",
  "ibt.jlopezc@gmail.com",
  "cristiangomez0686@outlook.com",
  "sashasawosz@hotmail.com",
  "nicocha2410@gmail.com",
  "leivanaomi.b@gmail.com",
  "fabiocroldan@gmail.com",
  "silvana.zalazar.dev@gmail.com",
  "barbara.martin.brown@gmail.com",
  "hebanano12@gmail.com",
  "mvillamayor099@gmail.com",
  "wnorowsky.nicolas@gmail.com",
  "silviainesvillalba@gmail.com",
  "verasdiegoca78@gmail.com",
  "contactame@rafaelaestevesg.com",
  "soto_tania@hotmail.com",
  "freddymoya2013@gmail.com",
  "fabricio.cbe@gmail.com",
  "miguel_gomez30@outlook.com",
  "martinkunbrc@hotmail.com",
  "molinamonroyv@gmail.com",
  "melirossi.mr@gmail.com",
  "angdavid2910@gmail.com",
  "jafetstivenlopezzuniga@gmail.com",
  "verobravo112012@gmail.com",
  "adrievelyn@gmail.com",
  "stiwers1997@gmail.com",
  "antho7294@gmail.com",
  "nr.rovere@gmail.com",
  "damian.fernandez.dev@gmail.com",
  "ing.elbaum@gmail.com",
  "ayelenfra9@gmail.com",
  "diego.productividad@gmail.com",
  "thomasignaciolopez@gmail.com",
  "veronica.derosa@gmail.com",
  "maximilianoingeniero@gmail.com",
  "chriscoronab@gmail.com",
  "silvanajaramillo90@gmail.com",
  "rafaelstrongoli@gmail.com",
  "leonelajazminsanchez@gmail.com",
  "pedrocerega@gmail.com",
  "mikeismerio@gmail.com",
  "emanuel_c400@hotmail.com",
  "leandrocano24@gmail.com",
  "tomas.agustin.friz@gmail.com",
  "mathiroldan@gmail.com",
  "tintinlp97@gmail.com",
  "naticanizatoral@gmail.com",
  "amontesvega2191@gmail.com",
  "santiagoo.vergaraa@gmail.com",
  "yordychoque124@gmail.com",
  "5843@holbertonstudents.com",
  "svrk73@gmail.com",
  "lorenavmaza@yahoo.es",
  "felipe.calderon321@gmail.com",
  "josemanuelhuautla@gmail.com",
  "lu.sol.rey@gmail.com",
  "alicia4079@gmail.com",
  "marcelyepesqf@gmail.com",
  "jpugapizarro@gmail.com",
  "alejandro5609@gmail.com",
  "scanevaro87@gmail.com",
  "spimentelm1201@gmail.com",
  "gastongomez2014@hotmail.com",
  "pabloelleproso@gmail.com",
  "orlandocardenas0107@gmail.com",
  "solpeloc@gmail.com",
  "danieldiaz-123@hotmail.com",
  "marcoslopezdev18@gmail.com",
  "jefpanchi@gmail.com",
  "augusto_dx@hotmail.com",
  "sergio-2k@hotmail.com",
  "manuelaramirez327@gmail.com",
  "cristiandalpiva@hotmail.com",
  "orilupellegrini@gmail.com",
  "cesar.s.mlopez@gmail.com",
  "goodfriend_18@hotmail.com",
  "ingeniera-yazuline@hotmail.com",
  "lazaronazareno@gmail.com",
  "jandrad38807@gmail.com",
  "szwallie26@gmail.com",
  "rubenldc1412@gmail.com",
  "alexmarinmendez@gmail.com",
  "fedemerediz@hotmail.com",
  "juansincich.design@gmail.com",
  "catriellescobar@gmail.com",
  "jhonatanjacome99@gmail.com",
  "omar.mejia2099@gmail.com",
  "mjparedes2505@gmail.com",
  "leonlederhossturich@gmail.com",
  "itsmarcos.1up@gmail.com",
  "mtmaisterra@gmail.com",
  "miltonoscarflores@gmail.com",
  "matcardillo91@hotmail.es",
  "marcosmateot@gmail.com",
  "amarantedaiana23@gmail.com",
  "lizaraz09@outlook.com",
  "mariagaa993@gmail.com",
  "ironmario25@hotmail.com",
  "cesar.hernandez9810@gmail.com",
  "jerangel1691@gmail.com",
  "medinafacundom@gmail.com",
  "benjapey99@gmail.com",
  "bautistaariza2001@gmail.com",
  "rociocarledev@gmail.com",
  "jesmoren1984@gmail.com",
  "adrianalaz@gmail.com",
  "caterin.mendez25@gmail.com",
  "dewinson12@gmail.com",
  "jona14carp@gmail.com",
  "data_analyst_jcq@outlook.com",
  "juanusca45@gmail.com",
  "dyakobowicz@gmail.com",
  "kevinquinones177@gmail.com",
  "alixeth.giacalone@gmail.com",
  "alixeth15@hotmail.com",
  "pachecoabimael360@gmail.com",
  "gerardo.carrizo123.gc@gmail.com",
  "jairo.josias14@gmail.com",
  "villenmj@gmail.com",
  "moreno.greenwater@gmail.com",
  "barbosanadi@gmail.com",
  "arelysacevedo@gmail.com",
  "alvaromirandamita@gmail.com",
  "javier17utn@gmail.com",
  "lunajosiasm@gmail.com",
  "monicadiazgarzon@gmail.com",
  "rodrigogeorgetti.cba@gmail.com",
  "chenhaohu555@gmail.com",
  "bralegz@gmail.com",
  "ariel.nicolas.aguilar@gmail.com",
  "brendacomasok@gmail.com",
  "david.castroanaya@gmail.com",
  "cynthiagarrido800@gmail.com",
  "gabrielakarinalopez01@gmail.com",
  "fabiannavarro218@gmail.com",
  "martuhcy@gmail.com",
  "nazarenodersho@gmail.com",
  "fevc1988@gmail.com",
  "jbetancourts976@gmail.com",
  "melanyracachaflores@gmail.com",
  "zaidraed@gmail.com",
  "luis.celletti@gmail.com",
  "alemanjuan741@gmail.com",
  "ponsmariaflorencia@gmail.com",
  "alopezdemora@gmail.com",
  "renzobozzini@gmail.com",
  "cmachuca32@gmail.com",
  "olozano99@itfip.edu.co",
  "parra.roger05@gmail.com",
  "ccasani93@gmail.com",
  "j.ibarralemp@outlook.es",
  "andresardila33@gmail.com",
  "fernandezjuanjc@gmail.com",
  "calebsenm@gmail.com",
  "g__56@hotmail.com",
  "rdminhot@gmail.com",
  "edgarin961@gmail.com",
  "natalypradomoreno@gmail.com",
  "marioandretybio@gmail.com",
  "alejaescalante1708@gmail.com",
  "juanpablo.qa@icloud.com",
  "pauli.sancho@gmail.com",
  "pmsaraalcantara@gmail.com",
  "cfacosta.15@gmail.com",
  "cesaramg.14@gmail.com",
  "mona62.qa@gmail.com",
  "juanjogiraldop254@gmail.com",
  "rodri.br18@gmail.com",
  "pablor.velasco.suarez@gmail.com",
  "damianothacehe@gmail.com",
  "freddo.el.rosh@gmail.com",
  "dev.ledg555@gmail.com",
  "marisolquinterosb@gmail.com",
  "lucianomolina970@gmail.com",
  "petterssonfacundo@gmail.com",
  "blanco.16ema@gmail.com",
  "maca.rabosto@gmail.com",
  "mateoscns@gmail.com",
  "emartinez.03@hotmail.com",
  "gonzipiccinini@gmail.com",
  "rotramon@hotmail.com",
  "jjcm@exatec.tec.mx",
  "mcarruitero@gmail.com",
  "wally8795@gmail.com",
  "andreccortes@gmail.com",
  "samudev01@gmail.com",
  "azarjpm15@gmail.com",
  "fdandreoli@gmail.com",
  "henrymilacrs@gmail.com",
  "sotopaguayj@gmail.com",
  "angelacba86@gmail.com",
  "manuelfilgueira@gmail.com",
  "facagre@gmail.com",
  "matias.nicolas.acevedo@gmail.com",
  "webenja0@gmail.com",
  "roddericckk@gmail.com",
  "sbenjacarias@gmail.com",
  "christian.kase@hotmail.com",
  "christian.ivan.cachero@gmail.com",
  "deivi.jimenez@gmail.com",
  "chrisday2009@hotmail.com",
  "luis37813@gmail.com",
  "mquirico10@gmail.com",
  "ricardoandrestolomei@gmail.com",
  "danitzavitoviz@gmail.com",
  "lrfernandez.cortez@gmail.com",
  "lupfaff3@gmail.com",
  "jtrvic7@gmail.com",
  "ronaldavid1908@hotmail.com",
  "csaggio74@hotmail.com",
  "javiercolodro@gmail.com",
  "ximenaellis@gmail.com",
  "giselalago@gmail.com",
  "deme12.1@gmail.com",
  "lguzman.58erb@outlook.com",
  "lizethvelasco.20@gmail.com",
  "johannmgr@gmail.com",
  "ad.contacto7@gmail.com",
  "leonasturizaga@gmail.com",
  "edslavianov@gmail.com",
  "juanignacionovas@gmail.com",
  "santigonzalez.dev@gmail.com",
  "conry.203@hotmail.com",
  "deydrim.dg@gmail.com",
  "francovangaray1@gmail.com",
  "pablo_spector@hotmail.com",
  "tomascolaz@gmail.com",
  "eddlogg@gmail.com",
];
const tieneMayuscula = (str) => /[A-Z]/.test(str);

// return;

let notFound = [];
async function checkEmails() {
  let memberNormalized = [];
  let token = process.env.TOKEN;
  // token = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxYjI2YzBiYmE4M2YzYTU5MWVmYmZiYiIsImFkbWluIjp0cnVlLCJpYXQiOjE2NjAwNzA4MzYsImV4cCI6MTY2MDMzMDAzNn0.nIPjdiTHSq1hnzDFV4oayffqqBQAOjPYQH0_e4W7yMM"
  const res = await axios.get(`${process.env.LOCALHOST}members`, {
    headers: { token: `Bearer ${token}` },
  });
  const members = res.data.getAllMembers;

  console.log(members.length);
  // return;

  // dataReviews.forEach((data) => {
  //   const encontrado = members.find((m) => m.email === data.email);
  //   if (encontrado) {
  //     //   console.log(email);
  //   } else {
  //     notFound.push(data.email);
  //     // console.log(data.email + "   " + data.nombre);
  //   }
  // });
  // const uniqueEmails = [...new Set(notFound)];
  // console.log(`Emails no encontrados: ${uniqueEmails.length}`);

  // uniqueEmails.forEach((element) => {
  //   if (tieneMayuscula(element)) {
  //     console.log(element + "      MAYUS");
  //   } else {
  //     console.log(element);
  //   }
  // });

  emails.forEach((data) => {
    const encontrado = members.find((m) => m.email === data);
    if (encontrado) {
      //   console.log(email);
    } else {
      console.log(data);
    }
  });
}
// }

checkEmails();
